Repository mash-up-kr/HGDGDS-Node, pull requests merged in 2025-06, with the labels that each got.

#10 Feat: Daily PR Summary to Slack Channel
  .github/workflows/daily_pr_summary.yml
Labels: Type:Setting

#24 Fix/cd
  .github/workflows/deploy.yml
Labels: Type:Bugfix

#37 [Feature] 파일관련 API 작업, api response 응답 처리
  .gitignore
  docs/files.md
  package.json
  src/app.config.ts
  src/common/constants/error-codes.ts
  src/common/database/config.ts
  src/common/exception/auth.exception.ts
  src/common/exception/base-exception.filter.ts
  src/common/exception/base.exception.ts
  src/common/exception/internal-server.exception.ts
  src/common/exception/request-parsing.exception.ts
  src/common/guard/global-auth.guard.ts
  src/common/interceptor/response.interceptor.ts
  src/files/files.controller.spec.ts
  src/files/files.controller.ts
  src/files/files.module.ts
  src/files/files.service.spec.ts
  src/files/files.service.ts
  src/files/request/access-presigned-url.request.ts
  src/files/request/upload-presigned-url.request.ts
  src/files/response/presigned.url.response.ts
  src/files/validator/file-prefix.validator.ts
  src/main.ts
  yarn.lock
Labels: Type:Feature

#44 #43 [FEAT]: 회원가입 및 로그인 API개발
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/dto/index.ts
  src/auth/dto/request/index.ts
  src/auth/dto/request/sign-in.dto.ts
  src/auth/dto/request/sign-up.dto.ts
  src/auth/dto/request/sign-up.request.dto.ts
  src/auth/dto/response/index.ts
  src/auth/dto/response/sign-up.response.ts
  src/common/enums/profile-image-code.ts
  src/common/enums/profile-image-name.ts
  src/docs/dto/auth.dto.ts
  src/files/files.module.ts
  src/users/dto/create-user.dto.ts
  src/users/dto/index.ts
  src/users/entities/user.entity.ts
  src/users/users.repository.ts
  yarn.lock
Labels: Type:Feature

#46 #45 [FEAT]: 유저 설정 변경 API 추가
  src/common/decorator/api-error-response.decorator.ts
  src/common/guard/global-auth.guard.spec.ts
  src/common/guard/global-auth.guard.ts
  src/docs/dto/user.dto.ts
  src/users/dto/request/update-user-settings.request.dto.ts
  src/users/dto/response/update-user-settings.response.ts
  src/users/users.controller.ts
  src/users/users.repository.ts
  src/users/users.service.ts
Labels: Type:Feature

#54 #53 [FEATURE] 예약 수정 API 추가
  src/common/exception/reservation.exception.ts
  src/docs/dto/reservation.dto.ts
  src/reservations/dto/request/update-reservation.request.ts
  src/reservations/dto/response/update-reservation.response.ts
  src/reservations/dto/update-reservation.dto.ts
  src/reservations/reservations.controller.ts
  src/reservations/reservations.service.ts
Labels: Type:Feature

#57 #56 [FEATURE] 예약 준비 완료 상태 변경API 추가
  src/common/constants/error-codes.ts
  src/common/exception/reservation.exception.ts
  src/reservations/dto/request/update.user.status.request.ts
  src/reservations/reservations.controller.ts
  src/reservations/reservations.service.ts
Labels: Type:Feature

#58 #52 [FEATURE] FCM 토큰 업데이트 API 추가
  src/migrations/1751105211041-AddFcmTokenToUsers.ts
  src/users/dto/request/update-fcm-token.dto.ts
  src/users/dto/response/update-fcm-token-response.dto.ts
  src/users/entities/user.entity.ts
  src/users/services/users.service.ts
  src/users/users.controller.ts
  src/users/users.repository.ts
Labels: Type:Feature
